"""
Government Schemes Knowledge Base for Dhvaani (Phase 6 - Verified Service Layer)
Contains major Indian central and state (Tamil Nadu) schemes.

All data here is VERIFIED and sourced from official government portals.
No invented eligibility, benefit amounts, URLs, or helpline numbers are allowed.

Phase 6 additions:
  scheme_id, official_name, local_names, benefits, exclusions,
  required_documents, official_application_url, official_information_url,
  official_helpline, ministry_or_department, source_type, source_url,
  last_verified, verification_status
"""

from typing import List, Dict, Optional, Any

GOVERNMENT_SCHEMES: List[Dict[str, Any]] = [   {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Visit the nearest Common Service Centre (CSC) or Krishi Vigyan Kendra',
                                 'OR apply online at pmkisan.gov.in',
                                 'Provide Aadhaar card, land records (Khasra/Khatauni), and bank passbook',
                                 'Submit the application form',
                                 'Receive confirmation SMS after registration'],
        'benefit': '₹6,000 per year in 3 equal installments of ₹2,000 directly to bank account',
        'benefits': '₹6,000 per year in 3 equal installments of ₹2,000 directly to bank account',
        'category': 'agriculture',
        'description': 'Direct income support of ₹6,000 per year (₹2,000 every 4 months) to small and marginal farmer '
                       'families.',
        'documents': ['Aadhaar Card', 'Land records/Khasra', 'Bank passbook', 'Mobile number'],
        'eligibility': [   'Small and marginal farmers owning up to 2 hectares of land',
                           'Must be an Indian citizen',
                           "Land must be in the farmer's name"],
        'exclusions': [   'Institutional land holders',
                          'Farmer families holding constitutional posts',
                          'Serving/retired government employees',
                          'Income tax payers',
                          'Professionals like doctors, engineers, lawyers, CAs'],
        'gender': ['male', 'female'],
        'helpline': 'PM-KISAN Helpline: 155261 / 011-24300606',
        'id': 'pm_kisan',
        'income_limit': None,
        'keywords': [   'farmer',
                        'kisan',
                        'agriculture',
                        'crop',
                        'farming',
                        'land',
                        'cultivation',
                        'financial support',
                        'income support',
                        'farming support',
                        'किसान',
                        'खेती',
                        'फसल',
                        'किसानी',
                        'விவசாயி',
                        'விவசாயம்',
                        'நிலம்',
                        'பயிர்',
                        'நிதி உதவி'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'प्रधानमंत्री किसान सम्मान निधि', 'ta': 'பிரதான் மந்திரி கிசான் சம்மான் நிதி'},
        'ministry': "Ministry of Agriculture & Farmers' Welfare",
        'ministry_or_department': "Ministry of Agriculture & Farmers' Welfare",
        'name': 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
        'name_hindi': 'प्रधानमंत्री किसान सम्मान निधि',
        'name_tamil': 'பிரதான் மந்திரி கிசான் சம்மான் நிதி',
        'not_eligible': [   'Institutional land holders',
                            'Farmer families holding constitutional posts',
                            'Serving/retired government employees',
                            'Income tax payers',
                            'Professionals like doctors, engineers, lawyers, CAs'],
        'occupation': ['farmer', 'kisan', 'agriculture', 'cultivation'],
        'official_application_url': 'https://pmkisan.gov.in/RegistrationFormupdated.aspx',
        'application_url': 'https://pmkisan.gov.in/RegistrationFormupdated.aspx',
        'status_url': 'https://pmkisan.gov.in/BeneficiaryStatus_New.aspx',
        'official_source_url': 'https://pmkisan.gov.in/',
        'official_helpline': '155261 / 011-24300606',
        'official_information_url': 'https://pmkisan.gov.in/',
        'official_name': 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
        'official_source': 'https://pmkisan.gov.in/',
        'required_documents': ['Aadhaar Card', 'Land records/Khasra', 'Bank passbook', 'Mobile number'],
        'scheme_id': 'pm_kisan',
        'source_type': 'central_portal',
        'source_url': 'https://pmkisan.gov.in/',
        'state': 'India',
        'target_groups': ['farmers', 'small farmers', 'marginal farmers', 'agricultural workers'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Check eligibility at pmjay.gov.in or call 14555',
                                 'Visit nearest Ayushman Mitra at empaneled hospital',
                                 'Provide Aadhaar or ration card',
                                 'Get Ayushman Bharat card (Golden Card)',
                                 'Use card for cashless treatment at any empaneled hospital'],
        'benefit': '₹5 lakh health coverage per year, cashless treatment at empaneled hospitals, covers pre and post '
                   'hospitalization',
        'benefits': '₹5 lakh health coverage per year, cashless treatment at empaneled hospitals, covers pre and post '
                    'hospitalization',
        'category': 'health',
        'description': "World's largest government-funded health insurance scheme providing coverage of ₹5 lakh per "
                       'family per year for secondary and tertiary care.',
        'documents': ['Aadhaar Card', 'Ration Card', 'Mobile number'],
        'eligibility': [   'Families listed in SECC 2011 database',
                           'Poor and vulnerable families',
                           'Families without any earning adult member aged 16-59',
                           'Daily wage laborers, construction workers, ragpickers',
                           'Scheduled Caste/Scheduled Tribe families'],
        'exclusions': [   'Families with government jobs',
                          'Those with income above poverty line who own motorized vehicles',
                          'Families owning 2.5+ acres of irrigated land'],
        'gender': ['male', 'female'],
        'helpline': '14555 / 1800-111-565',
        'id': 'ayushman_bharat',
        'income_limit': 'Below Poverty Line (SECC 2011 criteria)',
        'keywords': [   'health',
                        'hospital',
                        'medical',
                        'treatment',
                        'insurance',
                        'illness',
                        'sick',
                        'doctor',
                        'ayushman',
                        'pmjay',
                        'health insurance',
                        'family health',
                        'स्वास्थ्य',
                        'अस्पताल',
                        'इलाज',
                        'बीमारी',
                        'चिकित्सा',
                        'சுகாதாரம்',
                        'மருத்துவமனை',
                        'சிகிச்சை',
                        'நோய்',
                        'மருத்துவர்'],
        'last_verified': '2024-11-15',
        'local_names': {   'hi': 'आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना',
                           'ta': 'ஆயுஷ்மான் பாரத் - பிரதான் மந்திரி ஜன் ஆரோக்கிய யோஜனா'},
        'ministry': 'Ministry of Health and Family Welfare',
        'ministry_or_department': 'National Health Authority, Ministry of Health and Family Welfare',
        'name': 'Ayushman Bharat – PM Jan Arogya Yojana (PMJAY)',
        'name_hindi': 'आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना',
        'name_tamil': 'ஆயுஷ்மான் பாரத் - பிரதான் மந்திரி ஜன் ஆரோக்கிய யோஜனா',
        'not_eligible': [   'Families with government jobs',
                            'Those with income above poverty line who own motorized vehicles',
                            'Families owning 2.5+ acres of irrigated land'],
        'occupation': ['daily wage', 'labor', 'construction worker', 'ragpicker'],
        'official_application_url': 'https://beneficiary.nha.gov.in/',
        'application_url': 'https://beneficiary.nha.gov.in/',
        'status_url': 'https://beneficiary.nha.gov.in/',
        'official_source_url': 'https://pmjay.gov.in/',
        'official_helpline': '14555 / 1800-111-565',
        'official_information_url': 'https://pmjay.gov.in/',
        'official_name': 'Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)',
        'official_source': 'https://pmjay.gov.in/',
        'required_documents': ['Aadhaar Card', 'Ration Card', 'Mobile number'],
        'scheme_id': 'ayushman_bharat',
        'source_type': 'central_portal',
        'source_url': 'https://pmjay.gov.in/',
        'state': 'India',
        'target_groups': [   'poor families',
                             'bpl families',
                             'daily wage workers',
                             'sc/st families',
                             'vulnerable families'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Contact your Gram Panchayat or Block Development Officer (BDO)',
                                 'Name should be in SECC 2011 Awaiting List',
                                 'Fill PMAY-G application through Gram Sabha',
                                 'Bank account must be linked with Aadhaar',
                                 'Money transferred directly to your bank account in installments'],
        'benefit': '₹1.20 lakh in plain areas, ₹1.30 lakh in hilly/difficult areas for house construction',
        'benefits': '₹1.20 lakh in plain areas, ₹1.30 lakh in hilly/difficult areas for house construction',
        'category': 'housing',
        'description': 'Financial assistance to rural BPL families for construction of pucca (permanent) houses.',
        'documents': ['Aadhaar Card', 'Bank account details', 'Land documents (if available)', 'BPL card'],
        'eligibility': [   'Houseless families or those living in kutcha houses',
                           'Should be in SECC 2011 list',
                           'SC/ST, minorities, freed bonded laborers',
                           'Rural areas only',
                           'No existing pucca house'],
        'exclusions': [   'Urban area residents (they can apply for PMAY-Urban)',
                          'Families already receiving housing benefits',
                          'Families with income above BPL criteria'],
        'gender': ['male', 'female'],
        'helpline': '1800-11-6446',
        'id': 'pm_awas_yojana_rural',
        'income_limit': 'Below Poverty Line (BPL) / SECC 2011 list',
        'keywords': [   'house',
                        'home',
                        'housing',
                        'shelter',
                        'accommodation',
                        'pucca',
                        'construction',
                        'rural',
                        'घर',
                        'मकान',
                        'आवास',
                        'निर्माण',
                        'आश्रय',
                        'வீடு',
                        'குடியிருப்பு',
                        'கட்டுமானம்',
                        'புகலிடம்'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'प्रधानमंत्री आवास योजना - ग्रामीण', 'ta': 'பிரதான் மந்திரி ஆவாஸ் யோஜனா - கிராமீண'},
        'ministry': 'Ministry of Rural Development',
        'ministry_or_department': 'Ministry of Rural Development',
        'name': 'Pradhan Mantri Awaas Yojana – Gramin (PMAY-G)',
        'name_hindi': 'प्रधानमंत्री आवास योजना - ग्रामीण',
        'name_tamil': 'பிரதான் மந்திரி ஆவாஸ் யோஜனா - கிராமீண',
        'not_eligible': [   'Urban area residents (they can apply for PMAY-Urban)',
                            'Families already receiving housing benefits',
                            'Families with income above BPL criteria'],
        'occupation': [],
        'official_application_url': 'https://pmayg.nic.in/',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://pmayg.nic.in/',
        'official_helpline': '1800-11-6446',
        'official_information_url': 'https://pmayg.nic.in/',
        'official_name': 'Pradhan Mantri Awaas Yojana - Gramin (PMAY-G)',
        'official_source': 'https://pmayg.nic.in/',
        'required_documents': ['Aadhaar Card', 'Bank account details', 'Land documents (if available)', 'BPL card'],
        'scheme_id': 'pm_awas_yojana_rural',
        'source_type': 'central_portal',
        'source_url': 'https://pmayg.nic.in/',
        'state': 'India',
        'target_groups': ['bpl families', 'rural poor', 'houseless', 'sc/st families', 'rural residents'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': 18,
        'application_steps': [   'Visit nearest LPG distributor (HP/Bharat/Indane)',
                                 'Fill Ujjwala application form (KYC-1)',
                                 'Provide Aadhaar, BPL card, bank account details',
                                 'Self-declaration form for no existing LPG connection',
                                 'Connection approved within days'],
        'benefit': 'Free LPG connection with first refill and stove, EMI facility for refills',
        'benefits': 'Free LPG connection with first refill and stove, EMI facility for refills',
        'category': 'energy',
        'description': 'Free LPG connections to women from BPL households to move away from unhealthy cooking fuels.',
        'documents': ['Aadhaar Card', 'BPL ration card', 'Bank account details', 'Passport photo'],
        'eligibility': [   'Adult woman from BPL household',
                           'Should not already have an LPG connection',
                           'Name in SECC 2011 database or SC/ST/Most OBC/PM Awaas Yojana beneficiary',
                           'No existing LPG connection in household'],
        'exclusions': [   'Families already having an LPG connection',
                          'APL families',
                          'Urban households (some exceptions apply)'],
        'gender': ['female'],
        'helpline': '1906 / 1800-233-3555',
        'id': 'pm_ujjwala',
        'income_limit': 'Below Poverty Line (BPL) / SECC 2011',
        'keywords': [   'gas',
                        'lpg',
                        'cooking',
                        'cylinder',
                        'stove',
                        'fuel',
                        'ujjwala',
                        'kitchen',
                        'women gas',
                        'गैस',
                        'एलपीजी',
                        'रसोई',
                        'चूल्हा',
                        'सिलिंडर',
                        'வாயு',
                        'சமையல்',
                        'சிலிண்டர்',
                        'எரிபொருள்'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'प्रधानमंत्री उज्ज्वला योजना', 'ta': 'பிரதான் மந்திரி உஜ்வலா யோஜனா'},
        'ministry': 'Ministry of Petroleum and Natural Gas',
        'ministry_or_department': 'Ministry of Petroleum & Natural Gas',
        'name': 'Pradhan Mantri Ujjwala Yojana (PMUY)',
        'name_hindi': 'प्रधानमंत्री उज्ज्वला योजना',
        'name_tamil': 'பிரதான் மந்திரி உஜ்வலா யோஜனா',
        'not_eligible': [   'Families already having an LPG connection',
                            'APL families',
                            'Urban households (some exceptions apply)'],
        'occupation': [],
        'official_application_url': 'https://www.pmuy.gov.in/ujjwala2.html',
        'application_url': 'https://www.pmuy.gov.in/ujjwala2.html',
        'status_url': '',
        'official_source_url': 'https://www.pmuy.gov.in/',
        'official_helpline': '1800-266-6696 / 1906',
        'official_information_url': 'https://www.pmuy.gov.in/',
        'official_name': 'Pradhan Mantri Ujjwala Yojana 2.0 (PMUY)',
        'official_source': 'https://www.pmuy.gov.in/',
        'required_documents': ['Aadhaar Card', 'BPL ration card', 'Bank account details', 'Passport photo'],
        'scheme_id': 'pm_ujjwala',
        'source_type': 'central_portal',
        'source_url': 'https://www.pmuy.gov.in/',
        'state': 'India',
        'target_groups': ['women', 'bpl women', 'rural women', 'poor households'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': 18,
        'application_steps': [   'Visit your Gram Panchayat office',
                                 'Register your household for Job Card',
                                 'Provide family photo, Aadhaar, and address proof',
                                 'Receive Job Card within 15 days',
                                 'Apply for work whenever needed at Gram Panchayat',
                                 'Work must be provided within 15 days of application'],
        'benefit': '100 days of guaranteed employment per year, daily wage varies by state (₹200-350+)',
        'benefits': '100 days of guaranteed employment per year, daily wage varies by state (₹200-350+)',
        'category': 'employment',
        'description': 'Guarantees 100 days of wage employment per year to rural households whose adult members '
                       'volunteer to do unskilled manual work.',
        'documents': ['Aadhaar Card', 'Residence proof', 'Family photo'],
        'eligibility': [   'Adult members of any rural household',
                           'Willing to do unskilled manual work',
                           'Must register with local Gram Panchayat',
                           'Should be resident of the Gram Panchayat'],
        'exclusions': ['Urban residents', 'Those seeking skilled or semi-skilled work only'],
        'gender': ['male', 'female'],
        'helpline': '1800-111-555',
        'id': 'mahatma_gandhi_nrega',
        'income_limit': None,
        'keywords': [   'job',
                        'employment',
                        'work',
                        'mgnrega',
                        'nrega',
                        'wages',
                        'daily wage',
                        'labor',
                        'job card',
                        'rural employment',
                        'रोजगार',
                        'काम',
                        'नौकरी',
                        'मजदूरी',
                        'मजदूर',
                        'வேலை',
                        'வேலைவாய்ப்பு',
                        'கூலி',
                        'தொழிலாளர்'],
        'last_verified': '2024-11-15',
        'local_names': {   'hi': 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
                           'ta': 'மகாத்மா காந்தி தேசிய கிராமப்புற வேலைவாய்ப்பு உறுதி சட்டம்'},
        'ministry': 'Ministry of Rural Development',
        'ministry_or_department': 'Ministry of Rural Development',
        'name': 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
        'name_hindi': 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
        'name_tamil': 'மகாத்மா காந்தி தேசிய கிராமப்புற வேலைவாய்ப்பு உறுதி சட்டம்',
        'not_eligible': ['Urban residents', 'Those seeking skilled or semi-skilled work only'],
        'occupation': ['daily wage', 'labor', 'unskilled worker'],
        'official_application_url': 'https://nrega.nic.in/',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://nrega.nic.in/',
        'official_helpline': '1800-345-6565',
        'official_information_url': 'https://nrega.nic.in/',
        'official_name': 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
        'official_source': 'https://nrega.nic.in/',
        'required_documents': ['Aadhaar Card', 'Residence proof', 'Family photo'],
        'scheme_id': 'mahatma_gandhi_nrega',
        'source_type': 'central_portal',
        'source_url': 'https://nrega.nic.in/',
        'state': 'India',
        'target_groups': ['rural households', 'daily wage workers', 'rural poor', 'unemployed adults'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': 10,
        'application_steps': [   'Visit any bank branch or Business Correspondent',
                                 'Fill account opening form',
                                 'Provide Aadhaar (most banks accept Aadhaar as KYC)',
                                 'Account opened same day in most cases',
                                 'RuPay card delivered to address'],
        'benefit': 'Zero balance account, RuPay debit card, ₹2 lakh accident insurance, ₹30,000 life insurance, '
                   'overdraft facility up to ₹10,000',
        'benefits': 'Zero balance account, RuPay debit card, ₹2 lakh accident insurance, ₹30,000 life insurance, '
                    'overdraft facility up to ₹10,000',
        'category': 'banking',
        'description': 'Universal banking access with zero balance accounts, RuPay debit card, and accident insurance '
                       'coverage.',
        'documents': ['Aadhaar Card (sufficient for most banks)', 'Passport photo'],
        'eligibility': [   'Any Indian citizen above 10 years',
                           'No existing bank account (priority)',
                           'No income or documentation requirements'],
        'exclusions': ['No exclusions — open to all Indian citizens'],
        'gender': ['male', 'female'],
        'helpline': '1800-11-0001',
        'id': 'pm_jan_dhan',
        'income_limit': None,
        'keywords': [   'bank',
                        'account',
                        'savings',
                        'banking',
                        'zero balance',
                        'financial',
                        'jan dhan',
                        'debit card',
                        'rupay',
                        'बैंक',
                        'खाता',
                        'बचत',
                        'वित्तीय',
                        'வங்கி',
                        'கணக்கு',
                        'சேமிப்பு',
                        'நிதி'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'प्रधानमंत्री जन-धन योजना', 'ta': 'பிரதான் மந்திரி ஜன் தன் யோஜனா'},
        'ministry': 'Ministry of Finance',
        'ministry_or_department': 'Department of Financial Services, Ministry of Finance',
        'name': 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
        'name_hindi': 'प्रधानमंत्री जन-धन योजना',
        'name_tamil': 'பிரதான் மந்திரி ஜன் தன் யோஜனா',
        'not_eligible': ['No exclusions — open to all Indian citizens'],
        'occupation': [],
        'official_application_url': 'https://www.pmjdy.gov.in/',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://www.pmjdy.gov.in/',
        'official_helpline': '1800-11-0001 / 1800-180-1111',
        'official_information_url': 'https://www.pmjdy.gov.in/',
        'official_name': 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
        'official_source': 'https://www.pmjdy.gov.in/',
        'required_documents': ['Aadhaar Card (sufficient for most banks)', 'Passport photo'],
        'scheme_id': 'pm_jan_dhan',
        'source_type': 'central_portal',
        'source_url': 'https://www.pmjdy.gov.in/',
        'state': 'India',
        'target_groups': ['unbanked citizens', 'rural citizens', 'all citizens'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': 21,
        'application_steps': [   'Visit nearest Ration Shop or Village Administrative Officer (VAO)',
                                 'Carry ration card, Aadhaar, and bank details',
                                 'Fill application form',
                                 'Submit and get acknowledgment',
                                 'Amount credited monthly to linked bank account'],
        'benefit': '₹1,000 per month (₹12,000 per year) directly to bank account',
        'benefits': '₹1,000 per month (₹12,000 per year) directly to bank account',
        'category': 'women',
        'description': 'Tamil Nadu government scheme providing ₹1,000 per month to women heads of households as '
                       'financial support.',
        'documents': ['Aadhaar Card', 'Ration Card', 'Bank passbook', 'Passport photo'],
        'eligibility': [   'Women head of the household in Tamil Nadu',
                           'Age 21 and above',
                           'Household income below ₹2.5 lakh per year',
                           'Must have ration card',
                           'Tamil Nadu resident'],
        'exclusions': ['Government employees', 'Income tax payers', 'Those with pension above ₹1,000 per month'],
        'gender': ['female'],
        'helpline': 'Tamil Nadu Social Welfare: 044-28524785',
        'id': 'tamilnadu_kalaignar_insurance',
        'income_limit': 'Household income below ₹2.5 lakh per year',
        'keywords': [   'women',
                        'woman',
                        'female',
                        'lady',
                        'magalir',
                        'tamilnadu',
                        'tn scheme',
                        'financial support',
                        'monthly allowance',
                        'women allowance',
                        'महिला',
                        'औरत',
                        'பெண்',
                        'மகளிர்',
                        'பெண்கள்',
                        'தமிழ்நாடு',
                        'நிதி உதவி'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'कलैगनार मगलिर उरिमई थिट्टम (तमिलनाडु)', 'ta': 'கலைஞர் மகளிர் உரிமைத் திட்டம்'},
        'ministry': 'Government of Tamil Nadu – Social Welfare Department',
        'ministry_or_department': 'Special Programme Implementation Department, Government of Tamil Nadu',
        'name': 'Kalaignar Magalir Urimai Thittam (Tamil Nadu)',
        'name_hindi': 'कलैगनार मगलिर उरिमई थिट्टम (तमिलनाडु)',
        'name_tamil': 'கலைஞர் மகளிர் உரிமைத் திட்டம்',
        'not_eligible': ['Government employees', 'Income tax payers', 'Those with pension above ₹1,000 per month'],
        'occupation': [],
        'official_application_url': 'https://kmut.tn.gov.in/',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://kmut.tn.gov.in/',
        'official_helpline': '044-25619208',
        'official_information_url': 'https://kmut.tn.gov.in/',
        'official_name': 'Kalaignar Magalir Urimai Thittam (KMUT)',
        'official_source': 'https://kmut.tn.gov.in/',
        'required_documents': ['Aadhaar Card', 'Ration Card', 'Bank passbook', 'Passport photo'],
        'scheme_id': 'tamilnadu_kalaignar_insurance',
        'source_type': 'state_portal',
        'source_url': 'https://kmut.tn.gov.in/',
        'state': 'Tamil Nadu',
        'target_groups': ['women', 'women head of household', 'tamil nadu women'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': 40,
        'age_min': 18,
        'application_steps': [   'Visit your bank branch',
                                 'Fill APY registration form',
                                 'Provide Aadhaar, mobile number linked to bank account',
                                 'Choose pension amount (₹1000 to ₹5000)',
                                 'Contributions auto-debited monthly from bank account'],
        'benefit': 'Guaranteed pension of ₹1,000/₹2,000/₹3,000/₹4,000/₹5,000 per month after age 60, government '
                   'co-contribution for eligible',
        'benefits': 'Guaranteed pension of ₹1,000/₹2,000/₹3,000/₹4,000/₹5,000 per month after age 60, government '
                    'co-contribution for eligible',
        'category': 'pension',
        'description': 'Government-backed pension scheme for unorganized sector workers guaranteeing monthly pension '
                       'of ₹1,000 to ₹5,000 after age 60.',
        'documents': ['Aadhaar Card', 'Bank account passbook', 'Mobile number'],
        'eligibility': [   'Indian citizens aged 18-40 years',
                           'Must have savings bank account',
                           'Must not be income tax payer',
                           'Not covered under statutory social security schemes'],
        'exclusions': ['Government employees with pension', 'Income tax payers', 'Age above 40 or below 18'],
        'gender': ['male', 'female'],
        'helpline': '1800-110-069',
        'id': 'atal_pension_yojana',
        'income_limit': 'Must not be income tax payer',
        'keywords': [   'pension',
                        'retirement',
                        'old age',
                        'senior',
                        'elderly',
                        'atal pension',
                        'retirement savings',
                        'future savings',
                        'पेंशन',
                        'सेवानिवृत्ति',
                        'बुजुर्ग',
                        'वृद्धावस्था',
                        'ஓய்வூதியம்',
                        'முதுமை',
                        'வயோதிகம்',
                        'பென்சன்'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'अटल पेंशन योजना', 'ta': 'அடல் பென்சன் யோஜனா'},
        'ministry': 'Pension Fund Regulatory and Development Authority (PFRDA)',
        'ministry_or_department': 'Pension Fund Regulatory and Development Authority (PFRDA)',
        'name': 'Atal Pension Yojana (APY)',
        'name_hindi': 'अटल पेंशन योजना',
        'name_tamil': 'அடல் பென்சன் யோஜனா',
        'not_eligible': ['Government employees with pension', 'Income tax payers', 'Age above 40 or below 18'],
        'occupation': ['daily wage', 'self-employed', 'unorganized sector', 'informal'],
        'official_application_url': 'https://pfrda.org.in/web/pfrda/schemes/atal-pension-yojana-apy',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://pfrda.org.in/web/pfrda/schemes/atal-pension-yojana-apy',
        'official_helpline': '1800-110-069',
        'official_information_url': 'https://pfrda.org.in/web/pfrda/schemes/atal-pension-yojana-apy',
        'official_name': 'Atal Pension Yojana (APY)',
        'official_source': 'https://pfrda.org.in/web/pfrda/schemes/atal-pension-yojana-apy',
        'required_documents': ['Aadhaar Card', 'Bank account passbook', 'Mobile number'],
        'scheme_id': 'atal_pension_yojana',
        'source_type': 'central_portal',
        'source_url': 'https://pfrda.org.in/web/pfrda/schemes/atal-pension-yojana-apy',
        'state': 'India',
        'target_groups': ['unorganized workers', 'self-employed', 'informal sector workers'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Contact nearest bank, CSC, or crop insurance company',
                                 'Apply before cut-off date for sowing season',
                                 'Provide land records, crop sown details, and bank account',
                                 'Loanee farmers automatically covered through bank',
                                 'Claim through Gram Panchayat or online within 72 hours of crop loss'],
        'benefit': 'Insurance coverage for crop loss due to drought, flood, pest attack, etc. Premium is only 2% for '
                   'Kharif, 1.5% for Rabi crops',
        'benefits': 'Insurance coverage for crop loss due to drought, flood, pest attack, etc. Premium is only 2% for '
                    'Kharif, 1.5% for Rabi crops',
        'category': 'agriculture',
        'description': 'Crop insurance scheme that protects farmers against crop loss due to natural calamities, '
                       'pests, and diseases.',
        'documents': ['Aadhaar Card', 'Land records', 'Bank account', 'Crop sown details'],
        'eligibility': [   'All farmers including sharecroppers and tenant farmers',
                           'Mandatory for loanee farmers taking crop loans',
                           'Voluntary for non-loanee farmers'],
        'exclusions': ['Farmers who have not grown the notified crop in the area'],
        'gender': ['male', 'female'],
        'helpline': '1800-180-1551',
        'id': 'pm_fasal_bima',
        'income_limit': None,
        'keywords': [   'crop',
                        'insurance',
                        'fasal',
                        'harvest',
                        'damage',
                        'flood',
                        'drought',
                        'rain',
                        'crop insurance',
                        'farm insurance',
                        'farming insurance',
                        'crop loss',
                        'फसल',
                        'बीमा',
                        'बाढ़',
                        'सूखा',
                        'नुकसान',
                        'बारिश',
                        'பயிர்',
                        'காப்பீடு',
                        'வெள்ளம்',
                        'வறட்சி',
                        'மழை',
                        'சேதம்'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'प्रधानमंत्री फसल बीमा योजना', 'ta': 'பிரதான் மந்திரி ஃபசல் பீமா யோஜனா'},
        'ministry': "Ministry of Agriculture & Farmers' Welfare",
        'ministry_or_department': "Ministry of Agriculture & Farmers' Welfare",
        'name': 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        'name_hindi': 'प्रधानमंत्री फसल बीमा योजना',
        'name_tamil': 'பிரதான் மந்திரி ஃபசல் பீமா யோஜனா',
        'not_eligible': ['Farmers who have not grown the notified crop in the area'],
        'occupation': ['farmer', 'kisan', 'agriculture', 'cultivation', 'sharecropper'],
        'official_application_url': 'https://pmfby.gov.in/',
        'application_url': 'https://pmfby.gov.in/',
        'status_url': 'https://pmfby.gov.in/',
        'official_source_url': 'https://pmfby.gov.in/',
        'official_helpline': '14447 / 011-23382012',
        'official_information_url': 'https://pmfby.gov.in/',
        'official_name': 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        'official_source': 'https://pmfby.gov.in/',
        'required_documents': ['Aadhaar Card', 'Land records', 'Bank account', 'Crop sown details'],
        'scheme_id': 'pm_fasal_bima',
        'source_type': 'central_portal',
        'source_url': 'https://pmfby.gov.in/',
        'state': 'India',
        'target_groups': ['farmers', 'sharecroppers', 'tenant farmers'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Apply online at ksb.gov.in',
                                 'Upload required documents',
                                 'Verification by institution',
                                 'Selection based on merit'],
        'benefit': '₹2,500 per month for boys, ₹3,000 per month for girls',
        'benefits': '₹2,500 per month for boys, ₹3,000 per month for girls',
        'category': 'education',
        'description': 'Scholarships for children of Central Armed Police Forces martyrs and ex-servicemen for '
                       'professional courses.',
        'documents': ['Aadhaar Card', 'Mark sheets', 'Service certificate of parent', 'Bank details'],
        'eligibility': [   'Children/wards of Central Armed Police Forces ex-servicemen or martyrs',
                           'Minimum 60% marks in qualifying examination',
                           'First year of graduation/professional degree',
                           'Age limit as per scheme guidelines'],
        'exclusions': [   'Children of serving personnel (some exceptions)',
                          'Those pursuing correspondence/distance courses',
                          'Those already availing other scholarships'],
        'gender': ['male', 'female'],
        'helpline': '011-26173215',
        'id': 'pm_scholarship',
        'income_limit': None,
        'keywords': [   'scholarship',
                        'education',
                        'student',
                        'study',
                        'college',
                        'school',
                        'children',
                        'armed forces',
                        'police scholarship',
                        'capf scholarship',
                        'छात्रवृत्ति',
                        'शिक्षा',
                        'छात्र',
                        'पढ़ाई',
                        'स्कूल',
                        'कॉलेज',
                        'உதவித்தொகை',
                        'கல்வி',
                        'மாணவர்',
                        'படிப்பு',
                        'பள்ளி',
                        'கல்லூரி'],
        'last_verified': '2024-11-15',
        'local_names': {   'hi': 'केंद्रीय सशस्त्र पुलिस बलों के लिए पीएम छात्रवृत्ति योजना',
                           'ta': 'மத்திய ஆயுதப் போலீஸ் படைகளுக்கான பிரதமர் உதவித்தொகை திட்டம்'},
        'ministry': 'Ministry of Home Affairs / Kendriya Sainik Board',
        'ministry_or_department': 'Welfare and Rehabilitation Board (WARB) / Ministry of Education',
        'name': 'PM Scholarship Scheme for Central Armed Police Forces',
        'name_hindi': 'केंद्रीय सशस्त्र पुलिस बलों के लिए पीएम छात्रवृत्ति योजना',
        'name_tamil': 'மத்திய ஆயுதப் போலீஸ் படைகளுக்கான பிரதமர் உதவித்தொகை திட்டம்',
        'not_eligible': [   'Children of serving personnel (some exceptions)',
                            'Those pursuing correspondence/distance courses',
                            'Those already availing other scholarships'],
        'occupation': ['student'],
        'official_application_url': 'https://scholarships.gov.in/',
        'application_url': 'https://scholarships.gov.in/',
        'status_url': 'https://scholarships.gov.in/',
        'official_source_url': 'https://scholarships.gov.in/',
        'official_helpline': '0120-6619540',
        'official_information_url': 'https://scholarships.gov.in/',
        'official_name': "Prime Minister's Scholarship Scheme (PMSS) / National Scholarship Portal",
        'official_source': 'https://scholarships.gov.in/',
        'required_documents': ['Aadhaar Card', 'Mark sheets', 'Service certificate of parent', 'Bank details'],
        'scheme_id': 'pm_scholarship',
        'source_type': 'central_portal',
        'source_url': 'https://scholarships.gov.in/',
        'state': 'India',
        'target_groups': ['students', 'children of ex-servicemen', 'children of CAPF martyrs'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': 10,
        'age_min': 0,
        'application_steps': [   'Visit any post office or authorized bank',
                                 'Fill account opening form',
                                 "Provide girl child's birth certificate, parent's Aadhaar",
                                 'Minimum deposit ₹250 per year',
                                 'Account matures after 21 years from opening'],
        'benefit': 'High interest rate (currently ~8.2%), tax deduction under 80C, tax-free maturity amount',
        'benefits': 'High interest rate (currently ~8.2%), tax deduction under 80C, tax-free maturity amount',
        'category': 'women',
        'description': 'Small savings scheme for girl child education and marriage with high interest rate and tax '
                       'benefits.',
        'documents': ["Girl child's birth certificate", "Parent's Aadhaar", 'Passport photos', 'Address proof'],
        'eligibility': [   'Girl child below 10 years of age',
                           'Account opened by parent or guardian',
                           'One account per girl child, maximum two accounts per family'],
        'exclusions': [   'Girl children above 10 years of age',
                          'More than two girl children per family (exceptions for twins)'],
        'gender': ['female'],
        'helpline': 'India Post: 1800-425-2440',
        'id': 'sukanya_samriddhi',
        'income_limit': None,
        'keywords': [   'girl',
                        'daughter',
                        'girl child',
                        'sukanya',
                        'savings',
                        'marriage',
                        'education',
                        'girl savings',
                        'daughter savings',
                        'daughter scheme',
                        'बेटी',
                        'लड़की',
                        'बचत',
                        'बेटी बचाओ',
                        'विवाह',
                        'பெண் குழந்தை',
                        'மகள்',
                        'சேமிப்பு',
                        'திருமணம்'],
        'last_verified': '2024-11-15',
        'local_names': {'hi': 'सुकन्या समृद्धि योजना', 'ta': 'சுகன்யா சம்ரிதி யோஜனா'},
        'ministry': 'Ministry of Finance',
        'ministry_or_department': 'Department of Posts / Ministry of Finance',
        'name': 'Sukanya Samriddhi Yojana (SSY)',
        'name_hindi': 'सुकन्या समृद्धि योजना',
        'name_tamil': 'சுகன்யா சம்ரிதி யோஜனா',
        'not_eligible': [   'Girl children above 10 years of age',
                            'More than two girl children per family (exceptions for twins)'],
        'occupation': [],
        'official_application_url': 'https://www.indiapost.gov.in/',
        'application_url': '',
        'status_url': '',
        'official_source_url': 'https://www.indiapost.gov.in/',
        'official_helpline': '1800-266-6868',
        'official_information_url': 'https://www.indiapost.gov.in/',
        'official_name': 'Sukanya Samriddhi Yojana (SSY)',
        'official_source': 'https://www.indiapost.gov.in/',
        'required_documents': [   "Girl child's birth certificate",
                                  "Parent's Aadhaar",
                                  'Passport photos',
                                  'Address proof'],
        'scheme_id': 'sukanya_samriddhi',
        'source_type': 'central_portal',
        'source_url': 'https://www.indiapost.gov.in/',
        'state': 'India',
        'target_groups': ['girl child', 'daughters', 'parents of girl children'],
        'verification_status': 'verified',
        'verified': True},
    {   'age_max': None,
        'age_min': None,
        'application_steps': [   'Register at nearest government hospital or empaneled private hospital',
                                 'Carry ration card and Aadhaar',
                                 'Smart card issued for cashless treatment',
                                 'Use card at any empaneled hospital across Tamil Nadu'],
        'benefit': 'Up to ₹5 lakh per family per year for hospitalization, covers 1,000+ procedures',
        'benefits': 'Up to ₹5 lakh per family per year for hospitalization, covers 1,000+ procedures',
        'category': 'health',
        'description': 'Tamil Nadu government health insurance providing up to ₹5 lakh for families with annual income '
                       'below ₹72,000.',
        'documents': ['Ration Card', 'Aadhaar Card', 'Income certificate'],
        'eligibility': [   'Families with annual income below ₹72,000',
                           'Tamil Nadu residents with ration card',
                           'Covers family of 5 (can be extended)'],
        'exclusions': ['Government employees covered under CGHS', 'Families with income above ₹72,000'],
        'gender': ['male', 'female'],
        'helpline': '044-28452987',
        'id': 'tamilnadu_chief_minister_health_insurance',
        'income_limit': 'Annual family income below ₹72,000',
        'keywords': [   'health',
                        'hospital',
                        'insurance',
                        'tamilnadu',
                        'tn health',
                        'surgery',
                        'treatment',
                        'tamil nadu health',
                        'cm health insurance',
                        'स्वास्थ्य',
                        'बीमा',
                        'अस्पताल',
                        'சுகாதாரம்',
                        'காப்பீடு',
                        'மருத்துவமனை',
                        'அறுவை சிகிச்சை'],
        'last_verified': '2024-11-15',
        'local_names': {   'hi': 'मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना (तमिलनाडु)',
                           'ta': 'முதல்வர் விரிவான மருத்துவ காப்பீட்டுத் திட்டம்'},
        'ministry': 'Government of Tamil Nadu – Health Department',
        'ministry_or_department': 'Government of Tamil Nadu – Health and Family Welfare Department',
        'name': "Chief Minister's Comprehensive Health Insurance Scheme (Tamil Nadu)",
        'name_hindi': 'मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना (तमिलनाडु)',
        'name_tamil': 'முதல்வர் விரிவான மருத்துவ காப்பீட்டுத் திட்டம்',
        'not_eligible': ['Government employees covered under CGHS', 'Families with income above ₹72,000'],
        'occupation': [],
        'official_application_url': 'https://www.cmchistn.com/',
        'application_url': 'https://www.cmchistn.com/',
        'status_url': 'https://www.cmchistn.com/',
        'official_source_url': 'https://www.cmchistn.com/',
        'official_helpline': '1800-425-3993',
        'official_information_url': 'https://www.cmchistn.com/',
        'official_name': "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)",
        'official_source': 'https://www.cmchistn.com/',
        'required_documents': ['Ration Card', 'Aadhaar Card', 'Income certificate'],
        'scheme_id': 'tamilnadu_chief_minister_health_insurance',
        'source_type': 'state_portal',
        'source_url': 'https://www.cmchistn.com/',
        'state': 'Tamil Nadu',
        'target_groups': ['tamil nadu residents', 'low income families', 'bpl families'],
        'verification_status': 'verified',
        'verified': True}]

GRIEVANCE_DEPARTMENTS: Dict[str, Dict[str, Any]] = {   'education': {   'avg_resolution_days': 10,
                     'categories': ['teacher absence', 'school infrastructure', 'mid-day meal', 'scholarship issue'],
                     'helpline': 'School Education: 044-28272880',
                     'id': 'education',
                     'keywords': [   'school',
                                     'teacher',
                                     'education',
                                     'classroom',
                                     'mid day meal',
                                     'scholarship',
                                     'स्कूल',
                                     'शिक्षक',
                                     'शिक्षा',
                                     'मध्याह्न भोजन',
                                     'பள்ளி',
                                     'ஆசிரியர்',
                                     'கல்வி',
                                     'நள்ளிரவு உணவு'],
                     'name': 'School Education Department',
                     'name_hindi': 'विद्यालय शिक्षा विभाग',
                     'name_tamil': 'பள்ளிக் கல்வி துறை',
                     'portal': 'https://www.tnschools.gov.in/',
                     'priority': 'medium',
                     'priority_rules': [   'Child safety issue at school → urgent',
                                           'Teacher absent for >1 week → high',
                                           'Mid-day meal not served → high',
                                           'Infrastructure problem → medium']},
    'electricity': {   'avg_resolution_days': 3,
                       'categories': [   'power outage',
                                         'electricity bill',
                                         'meter issue',
                                         'sparking wire',
                                         'transformer fault'],
                       'helpline': 'TANGEDCO: 94987-94987 / 1912',
                       'id': 'electricity',
                       'keywords': [   'power cut',
                                       'no electricity',
                                       'voltage fluctuation',
                                       'meter',
                                       'bill',
                                       'connection',
                                       'transformer',
                                       'wire',
                                       'pole',
                                       'shock',
                                       'sparking',
                                       'power outage',
                                       'power failure',
                                       'no power',
                                       'electricity',
                                       'power',
                                       'blackout',
                                       'बिजली',
                                       'बिजली नहीं',
                                       'बिजली गुल',
                                       'मीटर',
                                       'बिल',
                                       'ट्रांसफार्मर',
                                       'करंट',
                                       'विद्युत',
                                       'மின்சாரம்',
                                       'மீட்டர்',
                                       'பில்',
                                       'மின்வெட்டு',
                                       'மின் கம்பி',
                                       'மின்சாரம் இல்லை'],
                       'name': 'Electricity Department / State Electricity Board',
                       'name_hindi': 'बिजली विभाग / राज्य विद्युत बोर्ड',
                       'name_tamil': 'மின்சாரம் துறை / மாநில மின்சார வாரியம்',
                       'portal': 'https://grievances.tneb.in/',
                       'priority': 'high',
                       'priority_rules': [   'Sparking wires or electric shock → urgent',
                                             'Sustained power cut (>4 hours) → high',
                                             'Billing dispute → medium']},
    'health': {   'avg_resolution_days': 3,
                  'categories': ['hospital complaint', 'medicine unavailability', 'PHC issue', 'ambulance'],
                  'helpline': 'Medical Helpline: 104 / Ambulance: 108',
                  'id': 'health',
                  'keywords': [   'hospital',
                                  'doctor',
                                  'medicine',
                                  'health',
                                  'ambulance',
                                  'PHC',
                                  'vaccination',
                                  'अस्पताल',
                                  'डॉक्टर',
                                  'दवाई',
                                  'टीका',
                                  'एम्बुलेंस',
                                  'மருத்துவமனை',
                                  'மருத்துவர்',
                                  'மருந்து',
                                  'சுகாதாரம்',
                                  'ஆம்புலன்ஸ்'],
                  'name': 'Health Department / Primary Health Centre',
                  'name_hindi': 'स्वास्थ्य विभाग / प्राथमिक स्वास्थ्य केंद्र',
                  'name_tamil': 'சுகாதாரம் துறை / ஆரம்ப சுகாதார மையம்',
                  'portal': 'https://www.tnhealth.tn.gov.in/',
                  'priority': 'high',
                  'priority_rules': [   'Medical emergency → call 108 immediately',
                                        'Medicine shortage at PHC → high',
                                        'Doctor absent → high',
                                        'Vaccination complaint → medium']},
    'municipal': {   'avg_resolution_days': 7,
                     'categories': [   'garbage collection',
                                       'drainage overflow',
                                       'sewage',
                                       'mosquito breeding',
                                       'sanitation'],
                     'helpline': 'GCC: 1913 / Urban Local Bodies: 1800-425-4788',
                     'id': 'municipal',
                     'keywords': [   'garbage',
                                     'waste',
                                     'cleaning',
                                     'sweeping',
                                     'drainage',
                                     'sewage',
                                     'mosquito',
                                     'sanitation',
                                     'कचरा',
                                     'सफाई',
                                     'सीवेज',
                                     'मच्छर',
                                     'குப்பை',
                                     'சுத்தம்',
                                     'கழிவு',
                                     'கொசு',
                                     'சாக்கடை'],
                     'name': 'Municipal Corporation / Local Body',
                     'name_hindi': 'नगर निगम / स्थानीय निकाय',
                     'name_tamil': 'நகராட்சி / உள்ளாட்சி அமைப்பு',
                     'portal': 'https://www.chennaicorporation.gov.in/',
                     'priority': 'medium',
                     'priority_rules': [   'Sewage overflow causing health hazard → urgent',
                                           'Garbage not collected for >1 week → high',
                                           'Mosquito/dengue breeding area → high',
                                           'General cleanliness → medium']},
    'police': {   'avg_resolution_days': 1,
                  'categories': ['crime', 'theft', 'harassment', 'missing person', 'accident'],
                  'helpline': 'Emergency: 100 / Women Helpline: 1091',
                  'id': 'police',
                  'keywords': [   'crime',
                                  'theft',
                                  'robbery',
                                  'assault',
                                  'harassment',
                                  'police',
                                  'accident',
                                  'missing',
                                  'अपराध',
                                  'चोरी',
                                  'डकैती',
                                  'उत्पीड़न',
                                  'पुलिस',
                                  'குற்றம்',
                                  'திருட்டு',
                                  'கொள்ளை',
                                  'தாக்குதல்',
                                  'போலீஸ்'],
                  'name': 'Police Department',
                  'name_hindi': 'पुलिस विभाग',
                  'name_tamil': 'போலீஸ் துறை',
                  'portal': 'https://eservices.tnpolice.gov.in/',
                  'priority': 'urgent',
                  'priority_rules': [   'Violence or immediate threat → urgent',
                                        'Theft or robbery → high',
                                        'Harassment → high',
                                        'Missing person → urgent']},
    'ration': {   'avg_resolution_days': 7,
                  'categories': ['ration not received', 'ration card issue', 'ration shop complaint', 'PDS problem'],
                  'helpline': 'Tamil Nadu Food: 1967 / 1800-425-5901',
                  'id': 'ration',
                  'keywords': [   'ration',
                                  'food',
                                  'rice',
                                  'ration card',
                                  'ration shop',
                                  'pds',
                                  'fair price',
                                  'राशन',
                                  'अनाज',
                                  'चावल',
                                  'राशन कार्ड',
                                  'उचित मूल्य',
                                  'ரேஷன்',
                                  'அரிசி',
                                  'ரேஷன் கடை',
                                  'நியாயவிலை'],
                  'name': 'Food and Civil Supplies Department / Ration Shop',
                  'name_hindi': 'खाद्य एवं नागरिक आपूर्ति विभाग',
                  'name_tamil': 'உணவு மற்றும் குடிமைப் பொருள் வழங்கல் துறை',
                  'portal': 'https://www.tnpds.gov.in/',
                  'priority': 'high',
                  'priority_rules': [   'Ration not provided for >2 weeks → high',
                                        'Ration card denied or cancelled → high',
                                        'Quantity shortfall → medium']},
    'revenue': {   'avg_resolution_days': 30,
                   'categories': ['land dispute', 'patta issue', 'encroachment', 'certificate', 'nativity certificate'],
                   'helpline': 'Revenue: 1800-425-1122',
                   'id': 'revenue',
                   'keywords': [   'land',
                                   'patta',
                                   'property',
                                   'encroachment',
                                   'certificate',
                                   'nativity',
                                   'community',
                                   'ज़मीन',
                                   'पट्टा',
                                   'संपत्ति',
                                   'अतिक्रमण',
                                   'प्रमाण पत्र',
                                   'நிலம்',
                                   'பட்டா',
                                   'சொத்து',
                                   'ஆக்கிரமிப்பு',
                                   'சான்றிதழ்'],
                   'name': 'Revenue Department / Collector Office',
                   'name_hindi': 'राजस्व विभाग / जिला कलेक्टर कार्यालय',
                   'name_tamil': 'வருவாய் துறை / மாவட்ட ஆட்சியர் அலுவலகம்',
                   'portal': 'https://tnreginet.gov.in/',
                   'priority': 'medium',
                   'priority_rules': [   'Active land encroachment → urgent',
                                         'Certificate needed for government scheme → high',
                                         'General land record dispute → medium']},
    'road': {   'avg_resolution_days': 15,
                'categories': ['pothole', 'road damage', 'drain overflow', 'manhole issue', 'footpath'],
                'helpline': 'PWD Helpline: 1800-425-0086',
                'id': 'road',
                'keywords': [   'road',
                                'pothole',
                                'pavement',
                                'footpath',
                                'drain',
                                'gutter',
                                'manhole',
                                'सड़क',
                                'गड्ढा',
                                'नाली',
                                'मैनहोल',
                                'சாலை',
                                'குழி',
                                'வடிகால்',
                                'மேன்ஹோல்'],
                'name': 'Public Works Department (PWD) / Municipal Corporation',
                'name_hindi': 'लोक निर्माण विभाग / नगर निगम',
                'name_tamil': 'பொது வேலைகள் துறை / நகராட்சி',
                'portal': 'https://pgportal.gov.in/',
                'priority': 'medium',
                'priority_rules': [   'Open manhole → urgent',
                                      'Pothole causing accidents → high',
                                      'General road damage → medium']},
    'streetlight': {   'avg_resolution_days': 5,
                       'categories': ['street light not working', 'public lighting issue'],
                       'helpline': 'GCC: 1913 / Urban Local Bodies: 1800-425-4788',
                       'id': 'streetlight',
                       'keywords': [   'street light',
                                       'streetlight',
                                       'road light',
                                       'lamp post',
                                       'no light on road',
                                       'pole light',
                                       'தெரு விளக்கு',
                                       'விளக்கு எரியவில்லை',
                                       'தெருவிளக்கு',
                                       'தெரு லைட்',
                                       'தெரு விளக்குகள்',
                                       'सड़क की लाइट',
                                       'स्ट्रीट लाइट',
                                       'स्ट्रीटलाइट',
                                       'गली की लाइट',
                                       'खंभे की लाइट'],
                       'name': 'Municipal Corporation / Local Body – Street Lighting',
                       'name_hindi': 'नगर निगम – स्ट्रीट लाइट',
                       'name_tamil': 'நகராட்சி – தெரு விளக்கு',
                       'portal': 'https://www.chennaicorporation.gov.in/',
                       'priority': 'medium',
                       'priority_rules': [   'Light near school or hospital → high',
                                             'Multiple lights in an area → high',
                                             'Single light not working → medium']},
    'water': {   'avg_resolution_days': 5,
                 'categories': ['water supply disruption', 'pipeline leak', 'water quality', 'no drinking water'],
                 'helpline': 'TWAD Board: 1800-425-1530',
                 'id': 'water',
                 'keywords': [   'water',
                                 'drinking water',
                                 'pipeline',
                                 'tap',
                                 'supply',
                                 'no water',
                                 'water quality',
                                 'पानी',
                                 'पाइप',
                                 'नल',
                                 'पेयजल',
                                 'தண்ணீர்',
                                 'குழாய்',
                                 'குடிநீர்',
                                 'நீர்'],
                 'name': 'Water Supply Department / Municipal Corporation',
                 'name_hindi': 'जल आपूर्ति विभाग / नगर निगम',
                 'name_tamil': 'குடிநீர் வழங்கல் துறை / நகராட்சி',
                 'portal': 'https://www.twadboard.tn.gov.in/',
                 'priority': 'high',
                 'priority_rules': [   'No drinking water for >2 days → high',
                                       'Contaminated water / water-borne disease risk → urgent',
                                       'Pipeline leak → high',
                                       'Irregular supply → medium']}}

def get_scheme_by_id(scheme_id: str) -> Optional[Dict[str, Any]]:
    for s in GOVERNMENT_SCHEMES:
        if s.get("id") == scheme_id or s.get("scheme_id") == scheme_id:
            return s
    return None

def get_verified_schemes() -> List[Dict[str, Any]]:
    return [s for s in GOVERNMENT_SCHEMES if s.get("verification_status") == "verified" or s.get("verified") is True]
